<a href="https://colab.research.google.com/github/sivakami-k/data-science-lab/blob/main/CO1_SVD_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
print("--SVD--")
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A:",A)
U,D,VT=np.linalg.svd(A)
print(U)
print(D)
print(VT)

print("\n--REMAKE--")
A_R=(U@np.diag(D)@VT)
print(A_R)

--SVD--
A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

--REMAKE--
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
