<a href="https://colab.research.google.com/github/sivakami-k/data-science-lab/blob/main/CO1_MatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("--ARRAY--")
print("1-D")
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a)

print("2-D")
b=np.array([[3,2],[5,8]])
print(b)

print("3-D")
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(type(c))
print(c)

print("\n--DIMENSION--")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(b.shape)
print(c.shape)

print("\n--ARANGE--")
a1=np.arange(1,7)
print(a1)

print("\n--RANDOM--")
import numpy as nm
from numpy import random as r
print(r.randint(100,size=(5)))
print(r.randint(100))
print(r.rand(7))
print(r.randint(0,100,6))

print("\n--INDEXING--")
m1=np.arange(2,9)
print(m1)
print(m1[4])
print(m1[4]+[6])
print(m1[-1])

print("\n--SLICING--")
m2=np.arange(2,10)
print(m2)
print(m2[3:9])
print(m2[:4])
print(m2[5:])

print("\n--RESHAPING--")
r1=np.arange(1,13)
print(r1)
x=r1.reshape(4,3)
print(x)

print("\n--SEARCH AND SORT--")
ar=np.array([1,2,8,5,4,9,7,3])
print(ar)
print(np.where(ar==4))
print(np.sort(ar))

print("\n--BASIC ARITHMATIC OPERATIONS--")
a=np.array([[3,3],[3,2]])
b=np.array([[9,6],[6,8]])
print("A=",a)
print("B=",b)
print("ADD")
print(np.add(a,b))
print("SUBTRACT")
print(np.subtract(b,a))
print("MULTIPLY")
print(np.multiply(a,b))
print("DIVISION")
print(np.divide(b,a))

print("\n--DOT AND TRANSPOSE--")
y=np.array([[[3,4,6],[7,6,3],[7,2,4]]])
z=np.array([[[1,2,3,],[6,4,3],[5,6,2]]])
print("y=",y)
print("z=",z)
print("DOT")
print(np.dot(a,b))
print("TRANSPOSE")
print(np.transpose(z))

print("\n--IDENTITY--")
i=np.identity(3,dtype=float)
print(i)
b2=np.ones([2,2],dtype=int)
print("ONES")
print(b2)
b3=np.zeros([2,2],dtype=int)
print("ZEROS")
print(b3)

print("\n--DETERMINANT AND INVERSE--")
k=np.array([[2,4,5],[6,7,2],[5,3,5]])
print("m=",k)
print("DET=",np.linalg.det(k))
print("INV:",np.linalg.inv(k))

--ARRAY--
1-D
[1 2 3 4 5 6 7 8]
2-D
[[3 2]
 [5 8]]
3-D
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

--DIMENSION--
1
2
3
(2, 2)
(1, 3, 3)

--ARANGE--
[1 2 3 4 5 6]

--RANDOM--
[76  7 34 19 26]
29
[0.82109472 0.40017772 0.79229272 0.55577429 0.80670437 0.69721114
 0.67784848]
[16 92 70 41 35 36]

--INDEXING--
[2 3 4 5 6 7 8]
6
[12]
8

--SLICING--
[2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[2 3 4 5]
[7 8 9]

--RESHAPING--
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

--SEARCH AND SORT--
[1 2 8 5 4 9 7 3]
(array([4]),)
[1 2 3 4 5 7 8 9]

--BASIC ARITHMATIC OPERATIONS--
A= [[3 3]
 [3 2]]
B= [[9 6]
 [6 8]]
ADD
[[12  9]
 [ 9 10]]
SUBTRACT
[[6 3]
 [3 6]]
MULTIPLY
[[27 18]
 [18 16]]
DIVISION
[[3. 2.]
 [2. 4.]]

--DOT AND TRANSPOSE--
y= [[[3 4 6]
  [7 6 3]
  [7 2 4]]]
z= [[[1 2 3]
  [6 4 3]
  [5 6 2]]]
DOT
[[45 42]
 [39 34]]
TRANSPOSE
[[[1]
  [6]
  [5]]

 [[2]
  [4]
  [6]]

 [[3]
  [3]
  [2]]]

--IDENTITY--
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
ONES
[[1 1]